name: Move new issues into Test 2 Project

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test 2
          column: Needs Triage
          repo-token: ${{ secrets.TOKEN }}
